apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: IBM-DevOps-ArgoCD
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'james-guestbook'
    spec:
      project: engineering-dev
      source:
        repoURL: https://github.com/jwcarmichael12/argo-cd/argo-cd.git
        targetRevision: HEAD
        path: applicationset/examples/list-generator/guestbook/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: engineering-dev
